### ISSUE TITLE
Mutation Policy Proposal

### ISSUE THREAD

**Issue by kd7lxl** [infobloxopen/tugger#10]
Currently, tugger's mutation policy uses simple substring matching to determine if a static private registry string will be prepended on the image name. By replacing this with a set of regex-based rewrite policies, many more use cases can be supported:
* substitute one private registry with another
* target a policy to a specific image
* translate characters in the image name (like replacing `.` with `-`)
* apply conditions to specific policies

Also, I think we can achieve a config that is easier to understand than the current config variables.

The policies will be stored in a ConfigMap and mounted into the container as a file like `policy.yaml`.

## Schema

```yaml
rewriteRules:
- pattern: regex
  replacement: template
  condition: policy
```

_pattern_ is a regex pattern

_replacement_ is a template comprised of the captured groups to use to generate the new image name. When _replacement_ is `null` or undefined, the image name is allowed without patching.

_condition_ is a special condition to test before committing the replacement. Initially `Always` and `Exists` will be supported. `Always` is the default and performs the replacement regardless of any condition. `Exists` implements the behavior from #7; it only rewrites the image name if the target name exists in the remote registry.

Each rule will be evaluated in order, and if the list is exhausted without a match, the admission controller will return `allowed: false`.

## Example

This example allows all images without rewriting:
```yaml
rewriteRules:
- pattern: .*
```

This example implements the existing behavior of rewriting all image names to start with `jainishshah17`:
```yaml
rewriteRules:
- pattern: ^jainishshah17/.*
- pattern: (.*)
  replacement: jainishshah17/$1
```

Or the same thing, but only if the image exists in `jainishshah17/`:
```yaml
rewriteRules:
- pattern: ^jainishshah17/.*
- pattern: (.*)
  replacement: jainishshah17/$1
  condition: Exists
- pattern: .*
```

Allow the nginx image, but rewrite everything else:
```yaml
rewriteRules:
- pattern: ^nginx(:.*)?$
- pattern: (?:jainishshah17)?(.*)
  replacement: jainishshah17/$1
```

cc @jainishshah17
